### ISSUE TITLE
[Feat] 상세페이지 작업

### ISSUE THREAD

**Issue by froggy1014** [dnd-side-project/dnd-11th-5-frontend#36]
## 📝 To-do

- [x] [Feat] 이미지 슬라이드
- [x] [Feat] 상단 상세정보
- [x] [Feat] 실시간 비활성화 채팅 컴포넌트
- [x] [Feat] 탭 공용 컴포넌트
- [x] [Feat] 상세내용 탭
- [x] [Feat] 리뷰 탭
- [x] [Feat] 주변정보 탭 (카카오 지도 연동)
