### ISSUE TITLE
[Feat] 퍼널 형식 온보딩

### ISSUE THREAD

**Issue by froggy1014** [dnd-side-project/dnd-11th-5-frontend#6]
## 🛠 Issue

 온보딩을 위해 뼈대 구성

## 📝 To-do

- [x] On-boarding Component 작성
- [x] React Hook Form, zod 연동해서 간단하게 구성

- [x] serverAction으로 리스트 페칭해오기
- [x] canvas-confetti를 이용한 완료 애니메이션 
      - https://www.npmjs.com/package/canvas-confetti
- [x] 결과 로딩 페이지 Stagger 모션 추가
- [x] Redirect 버튼 및 받아온 이미지 렌더
